const GET_ROOT = "GET_ROOT";
const ADD_NODE = "ADD_NODE";
const GET_CHILD_NODES = "GET_CHILD_NODES";
const GET_NODE = "GET_NODE";
const EDIT_NODE = "EDIT_NODE";
const DELETE_NODE = "DELETE_NODE";
const DELETE_ROOTED_NODE = "DELETE_ROOTED_NODE";

const SHOW_MODAL = "SHOW_MODAL";
const HIDE_MODAL = "HIDE_MODAL";

export {
  GET_ROOT,
  ADD_NODE,
  GET_CHILD_NODES,
  GET_NODE,
  EDIT_NODE,
  DELETE_NODE,
  SHOW_MODAL,
  HIDE_MODAL,
  DELETE_ROOTED_NODE,
};
